const {chromium,webkit}=require('playwright');const assert=require('assert');const fs=require('fs');const base=process.env.QA_BASE||'http://127.0.0.1:18749/';
(async()=>{const report={base,checks:[]};
for(const [engine,type] of [['Chromium',chromium],['WebKit',webkit]]){
 const browser=await type.launch();const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'});const p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(String(e)));
 async function check(name,fn){await fn();report.checks.push(engine+': '+name);console.log('PASS',engine,name)}
 await check('Portada compacta, índice móvil y vista ilustrada',async()=>{await p.goto(base);assert.equal(await p.locator('body').getAttribute('data-catalog-view'),'compact');const first=await p.evaluate(()=>document.querySelector('.story-card').offsetTop);assert(first<1300);assert(await p.evaluate(()=>document.documentElement.scrollHeight<11000));await p.getByRole('button',{name:'Ver ilustraciones',exact:true}).click();assert.equal(await p.locator('body').getAttribute('data-catalog-view'),'cards');await p.getByRole('button',{name:'Índice rápido',exact:true}).click()});
 await check('Regreso conserva consulta, categoría, vista y tarjeta',async()=>{await p.getByRole('button',{name:'Cartas',exact:true}).click();await p.locator('#search').fill('Remedios');const card=p.locator('.story-card:visible').first();await card.scrollIntoViewIfNeeded();const id=await card.getAttribute('id');await card.locator('a').click();await p.locator('.reader-tools a').click();assert.equal(await p.locator('#search').inputValue(),'Remedios');assert.equal(await p.locator('[data-filter="Cartas"]').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('body').getAttribute('data-catalog-view'),'compact');assert(await p.locator('#'+id).isVisible());await p.waitForTimeout(80);const pos=await p.locator('#'+id).boundingBox();assert(pos.y<844&&pos.y+pos.height>0);await p.reload();assert.equal(await p.locator('#search').inputValue(),'Remedios')});
 await check('Escala de texto coherente en navegación, búsqueda y botones',async()=>{await p.goto(base);const sizes=[];for(const f of ['normal','large','extra']){await p.locator('[data-settings]').first().click();await p.locator('button[data-font="'+f+'"]').click();await p.locator('[data-close-settings]').click();await p.waitForTimeout(60);sizes.push(await p.evaluate(()=>['.filters button','#search','.font-toggle','.read-label'].map(s=>parseFloat(getComputedStyle(document.querySelector(s)).fontSize))))}for(let j=0;j<4;j++)assert(sizes[0][j]<sizes[1][j]&&sizes[1][j]<sizes[2][j]);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1))});
 const url=base+'relatos/el-ultimo-golpe-en-el-yunque.html';
 async function point(){return p.evaluate(()=>{const a=[...document.querySelectorAll('#story-text p,#story-text h2')];const i=a.findIndex(e=>e.getBoundingClientRect().bottom>24);const r=a[i].getBoundingClientRect();return {index:i,ratio:(24-r.top)/r.height,y:scrollY}})}
 await check('Cambiar letra y tema conserva el párrafo y su avance',async()=>{await p.goto(url);await p.evaluate(()=>{const s=document.querySelector('#story-text');scrollTo({top:s.offsetTop+s.offsetHeight*.6,behavior:'instant'})});await p.waitForTimeout(220);const before=await point();assert(before.index>3);await p.locator('.reader-tools [data-settings]').click();await p.locator('button[data-font="normal"]').click();await p.locator('button[data-theme="night"]').click();await p.keyboard.press('Escape');await p.waitForTimeout(100);const after=await point();assert.equal(after.index,before.index);assert(Math.abs(after.ratio-before.ratio)<.02);const stored=await p.evaluate(()=>JSON.parse(localStorage.getItem('fernando-relatos:anchor:el-ultimo-golpe-en-el-yunque')));assert.equal(stored.index,before.index);await p.goto(base);await p.locator('#continue-reading').click();await p.waitForTimeout(100);const resumed=await point();assert.equal(resumed.index,before.index);assert(Math.abs(resumed.ratio-before.ratio)<.02)});
 await check('Los huecos entre párrafos conservan el siguiente párrafo al ajustar y retomar',async()=>{
  await p.goto(base+'relatos/contrastes-entre-el-pasado-y-el-presente.html');
  await p.evaluate(()=>{const el=document.querySelectorAll('#story-text p')[5];scrollTo({top:scrollY+el.getBoundingClientRect().top-39,behavior:'instant'})});await p.waitForTimeout(200);
  let stored=await p.evaluate(()=>JSON.parse(localStorage.getItem('fernando-relatos:anchor:contrastes-entre-el-pasado-y-el-presente')));assert.equal(stored.index,5);assert.equal(stored.ratio,0);
  await p.locator('.reader-tools [data-settings]').click();await p.locator('button[data-font="extra"]').click();await p.keyboard.press('Escape');await p.waitForTimeout(100);
  assert(Math.abs((await p.locator('#story-text p').nth(5).boundingBox()).y-39)<3);
  await p.goto(base);await p.locator('#continue-reading').click();await p.waitForTimeout(100);
  assert(Math.abs((await p.locator('#story-text p').nth(5).boundingBox()).y-39)<3);
 });
 await check('Barra visible durante lectura y final no oculto',async()=>{await p.evaluate(()=>scrollBy({top:500,behavior:'instant'}));const r=await p.locator('.reader-tools').boundingBox();assert(r.y>=0&&r.y+r.height<=845);for(const el of await p.locator('.reader-tools a,.reader-tools button:visible').all()){const q=await el.boundingBox();assert(q.height>=48);assert(q.y>=0&&q.y+q.height<=845)}await p.locator('.site-footer').scrollIntoViewIfNeeded();assert(await p.evaluate(()=>document.body.scrollHeight>document.querySelector('.site-footer').offsetTop+document.querySelector('.site-footer').offsetHeight))});
 await check('Ilustración pequeña con descripción y diálogo accesible',async()=>{await p.goto(base+'relatos/copa-gigante.html');assert(await p.locator('.image-quality').isVisible());await p.locator('.image-description summary').click();assert((await p.locator('.image-description>div').textContent()).length>100);assert((await p.locator('.story-figure img').getAttribute('alt')).length>45);await p.locator('.zoom-image').click();await p.locator('#zoom-in').click();await p.keyboard.press('Escape');assert(!(await p.locator('#image-dialog').isVisible()))});
 await check('Reflujo a 320 px y móvil horizontal con fuente extra',async()=>{for(const [width,height] of [[320,568],[844,390]]){await p.setViewportSize({width,height});await p.goto(url);await p.locator('.reader-tools [data-settings]').click();await p.locator('button[data-font="extra"]').click();await p.locator('[data-close-settings]').click();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.evaluate(()=>scrollTo({top:1500,behavior:'instant'}));const r=await p.locator('.reader-tools').boundingBox();assert(r.height<=height*.45+1);assert(r.y>=0)}});
 await check('Zoom textual al 200 %, panel e imagen siguen utilizables',async()=>{await p.setViewportSize({width:320,height:640});await p.goto(base+'relatos/haikus.html');await p.addStyleTag({content:'html{font-size:200% !important}'});await p.locator('.reader-tools [data-settings]').click();assert(await p.locator('[data-close-settings]').isVisible());await p.keyboard.press('Escape');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.locator('.zoom-image').first().click();const fits=await p.evaluate(()=>{const d=document.querySelector('#image-dialog'),r=d.getBoundingClientRect(),x=document.querySelector('#close-image').getBoundingClientRect();return x.bottom<=r.bottom&&x.right<=r.right&&document.querySelector('.image-scroll').clientHeight>80});assert(fits);await p.keyboard.press('Escape')});
 assert.equal(errors.length,0,errors.join('\n'));await context.close();await browser.close();
}
// Test playback controls with a deterministic device-API double; does not certify real audio.
const b=await chromium.launch();const p=await b.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});await p.addInitScript(()=>{window.voiceCalls=[];class Utterance{constructor(text){this.text=text}};Object.defineProperty(window,'SpeechSynthesisUtterance',{value:Utterance});Object.defineProperty(window,'speechSynthesis',{value:{getVoices:()=>[{lang:'es-ES'}],speak:u=>{window.voiceCalls.push('speak');window.lastUtterance=u},pause:()=>window.voiceCalls.push('pause'),resume:()=>window.voiceCalls.push('resume'),cancel:()=>window.voiceCalls.push('cancel')}})});await p.goto(base+'relatos/la-peonza-inmovil.html');await p.locator('#listen').click();await p.evaluate(()=>scrollTo({top:1600,behavior:'instant'}));await p.locator('#listen').click();assert.equal(await p.locator('#listen').innerText(),'Continuar');await p.locator('#listen').click();await p.locator('#stop-listening').click();assert.equal(await p.locator('#listen').innerText(),'Escuchar');assert(await p.locator('#stop-listening').isHidden());assert((await p.evaluate(()=>window.voiceCalls)).includes('pause'));report.checks.push('Controles de voz probados con API simulada');await b.close();
fs.writeFileSync('qa/ux-regression-report.json',JSON.stringify(report,null,2));console.log('SUCCESS',report.checks.length)})().catch(e=>{console.error(e);process.exit(1)});
