const { chromium, webkit } = require('playwright');
const fs=require('fs');const path=require('path');const assert=require('assert');
const root=path.resolve(__dirname,'..');const data=JSON.parse(fs.readFileSync(path.join(root,'source','collection.json'),'utf8'));const base=process.env.QA_BASE||'http://127.0.0.1:18749/';
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1050},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url())});
await page.goto(base);await page.screenshot({path:path.join(root,'qa','home-desktop.png'),fullPage:false});
const result={base,checks:[],errors};
async function check(name,fn){await fn();result.checks.push(name);console.log('PASS',name)}
await check('24 textos + prólogo, navegación y sin errores',async()=>{assert.equal(await page.locator('.story-card').count(),24);assert.equal(await page.locator('h1').count(),1)});
await check('Filtros, búsqueda sin tildes y recuperación del vacío',async()=>{await page.getByRole('button',{name:'Cartas',exact:true}).click();assert.equal(await page.locator('.story-card:visible').count(),2);await page.locator('#search').fill('zzzzzz');await page.locator('#no-results').waitFor({state:'visible'});await page.locator('#reset-search').click();assert.equal(await page.locator('.story-card:visible').count(),24);await page.locator('#search').fill('peonza');assert.equal(await page.locator('.story-card:visible').count(),1);await page.locator('#search').fill('')});
for(const width of [320,390,768,1440])await check('Portada sin desbordamiento a '+width,async()=>{await page.setViewportSize({width,height:844});await page.goto(base);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));if(width===390){await page.screenshot({path:path.join(root,'qa','home-mobile.png'),fullPage:false});await page.locator('#coleccion').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(root,'qa','collection-mobile.png')})}});
await check('Texto íntegro de las 25 páginas y todas las imágenes cargan',async()=>{for(const s of data){await page.goto(base+'relatos/'+s.id+'.html');const rendered=(await page.locator('#story-text p, #story-text h2').allTextContents()).join(' ');const actual=rendered.replace(/\s/g,'');const expected=s.paragraphs.filter(p=>p.type!=='caption').map(p=>p.text).join('').replace(/\s/g,'');assert.equal(actual,expected,s.id);await page.locator('.site-footer').scrollIntoViewIfNeeded();await page.evaluate(()=>Promise.all([...document.images].filter(im=>im.getAttribute('src')).map(im=>{im.loading='eager';return im.decode().catch(()=>{})})));assert(await page.evaluate(()=>[...document.images].filter(im=>im.getAttribute('src')).every(i=>i.complete&&i.naturalWidth>0)),s.id);assert.equal(await page.locator('h1').count(),1,s.id)}});
await page.setViewportSize({width:390,height:844});await page.goto(base+'relatos/la-peonza-inmovil.html');
await check('Letra muy grande, contraste, persistencia y lectura móvil',async()=>{await page.locator('[data-settings]').first().click();await page.getByRole('button',{name:'Muy grande',exact:true}).click();await page.getByRole('button',{name:'Alto contraste',exact:true}).click();assert.equal(await page.locator('body').getAttribute('data-font'),'extra');await page.reload();assert.equal(await page.locator('body').getAttribute('data-font'),'extra');assert.equal(await page.locator('body').getAttribute('data-theme'),'contrast');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.locator('#story-text').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(root,'qa','reader-mobile-extra.png')})});
await check('Imagen ampliable y cierre con Escape devuelve foco',async()=>{const link=page.locator('.zoom-image').first();await link.click();await page.locator('#image-dialog').waitFor({state:'visible'});await page.locator('#zoom-in').click();await page.keyboard.press('Escape');assert(!(await page.locator('#image-dialog').isVisible()));assert.equal(await page.evaluate(()=>document.activeElement.className),'zoom-image')});
await check('Guardar avance y volver a lectura',async()=>{await page.locator('#story-text').scrollIntoViewIfNeeded();await page.evaluate(()=>scrollBy(0,800));await page.waitForTimeout(350);await page.goto(base);await page.locator('#continue-reading').waitFor({state:'visible'});await page.locator('#continue-reading').click();assert(page.url().includes('la-peonza-inmovil.html#seguir'));await page.waitForTimeout(100);assert(await page.evaluate(()=>scrollY>300))});
await check('Relato aleatorio abre página válida',async()=>{await page.goto(base);await page.locator('[data-random]').first().click();await page.waitForURL('**/relatos/*.html');assert(await page.locator('#story-text').isVisible())});
await check('Ampliación al 200 por ciento sin desbordamiento',async()=>{await page.setViewportSize({width:390,height:844});await page.goto(base+'relatos/haikus.html');await page.addStyleTag({content:'html{font-size:200%}'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1))});
await page.setViewportSize({width:1440,height:1050});await page.goto(base+'relatos/el-ultimo-golpe-en-el-yunque.html');await page.evaluate(()=>{document.body.dataset.font='large';document.body.dataset.theme='paper'});await page.screenshot({path:path.join(root,'qa','reader-desktop.png')});
await check('Lectura básica sin JavaScript',async()=>{const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const p=await nojs.newPage();await p.goto(base);assert.equal(await p.locator('.story-card').count(),24);await p.goto(base+'relatos/haikus.html');assert.equal(await p.locator('.haiku').count(),3);assert(await p.locator('#story-text').isVisible());await nojs.close()});
assert.equal(errors.length,0,errors.join('\n'));await browser.close();
try{const b=await webkit.launch({headless:true});const p=await b.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await p.goto(base);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.locator('.story-card a').first().click();await p.locator('#story-text').waitFor();await p.locator('[data-settings]').first().click();await p.getByRole('button',{name:'Muy grande',exact:true}).click();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));result.checks.push('WebKit móvil: navegación táctil y letra muy grande');await b.close()}catch(e){result.webkit=String(e);throw e}
fs.writeFileSync(path.join(root,'qa','browser-report.json'),JSON.stringify(result,null,2));console.log('SUCCESS',result.checks.length,'checks');})().catch(e=>{console.error(e);process.exit(1)});
